name: dfa-py311-cu126
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - torchaudio==2.9.1+cu126
      - numpy==1.23.5
      - opencv-python==4.11.0.86
      - onnxruntime-gpu==1.24.3
      - insightface==0.7.3
